"""
NIST AI RMF Profile document template.

Generates a NIST AI RMF profile document for an AI system,
mapping its EU AI Act classification to NIST core functions.
"""

from __future__ import annotations

from app.modules.compliance.nist_mapping import (
    EU_TO_NIST_MAPPING,
    NIST_AI_RMF_METADATA,
    NIST_CORE_FUNCTIONS,
)


def generate_nist_rmf_profile(
    system_name: str,
    system_description: str,
    eu_risk_level: str,
    organization: str = "Your Organization",
) -> str:
    """Generate a NIST AI RMF profile document as markdown."""
    mapping = EU_TO_NIST_MAPPING.get(eu_risk_level.upper(), {})
    meta = NIST_AI_RMF_METADATA

    lines = [
        f"# NIST AI RMF Profile — {system_name}",
        f"**Organization:** {organization}",
        f"**Framework:** {meta['name']} {meta['version']} ({meta['published']})",
        f"**EU AI Act Risk Tier:** {eu_risk_level}",
        f"**NIST Risk Tier:** {mapping.get('nist_risk_tier', 'Unknown')}",
        "",
        "---",
        "",
        "## System Overview",
        f"{system_description}",
        "",
        "---",
        "",
        "## Applicable NIST AI RMF Core Functions",
        "",
    ]

    for fn in mapping.get("primary_functions", []):
        desc = NIST_CORE_FUNCTIONS.get(fn, "")
        lines += [f"### {fn}", desc, ""]

    lines += [
        "---",
        "",
        "## Required Actions by Subcategory",
        "",
    ]

    for sub in mapping.get("subcategories", []):
        lines.append(f"- {sub}")

    lines += [
        "",
        "---",
        "",
        "## Rationale",
        mapping.get("rationale", ""),
        "",
        "---",
        "",
        f"*Generated by AegisAI — {meta['name']} {meta['version']}*",
        f"*Reference: {meta['url']}*",
    ]

    return "\n".join(lines)